=== abelcetus/PlantPlaces18FS001/PlantPlaces18FS001/PlantPlaces18FS001/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="plant">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="genus" type="xs:string"/>
        <xs:element name="species" type="xs:string" minOccurs="0" default="spp."/>
        <xs:element name="cultivar" type="xs:string" minOccurs="0"/>
        <xs:element name="common_name" type="xs:string" minOccurs="0"/>
        <xs:element name="height" type="xs:integer" minOccurs="0"/>
		<xs:element name="begin_bloom_date" type="xs:date" minOccurs="0"/>
		<xs:element name="end_bloom_date" type="xs:date" minOccurs="0"/>
        <xs:element ref="specimens"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="specimens">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="specimen" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="specimen">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="latitude" type="xs:string"/>
        <xs:element name="longitude" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="planted_by" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== abelcetus/PlantPlaces18FS001/PlantPlaces18FS001/PlantPlaces18FS001/plants.xml
<?xml version="1.0" encoding="utf-8" ?>
<plant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="plants.xsd"> 
  <genus>Asimina</genus>
  <species>triloba</species>
  <cultivar>Potomac</cultivar>
  <common_name>Pawpaw</common_name>
  <height>40</height>
  <sun_tolerance>full_sun</sun_tolerance>
  <bloom_color>blue</bloom_color>
  <specimens>
    <specimen>
      <latitude>39.74</latitude>
      <longitude>-84.51</longitude>
      <description>A beautiful specimen, planted in 2008</description>
      <planted_by>Checkers</planted_by>
    </specimen>
    <specimen>
      <latitude>38.54</latitude>
      <longitude>-84.49</longitude>
      <description>In Fruit!</description>
      <planted_by>Bugsy</planted_by>
    </specimen>

  </specimens>
</plant>
